tried moving docker to python3 but tests fail
tests fail due to python3 string changes, e.g.

...
======================================================================
ERROR: test_bin_long_bam_file_name (__main__.SingleFullReadBamTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "bamliquidatorbatch/test.py", line 352, in test_bin_long_bam_file_name
    bam_file_path = long_file_path)
  File "/opt/liquidator/bamliquidatorbatch/bamliquidator_batch.py", line 256, in __init__
    self.batch(extension, sense)
  File "/opt/liquidator/bamliquidatorbatch/bamliquidator_batch.py", line 208, in batch
    self.normalize()
  File "/opt/liquidator/bamliquidatorbatch/bamliquidator_batch.py", line 283, in normalize
    nps.normalize_plot_and_summarize(counts_file, self.output_directory, self.bin_size, self.skip_plot)
  File "/opt/liquidator/bamliquidatorbatch/normalize_plot_and_summarize.py", line 412, in normalize_plot_and_summarize
    plot(output_directory, normalized_counts, chromosome, cell_types)
  File "/opt/liquidator/bamliquidatorbatch/normalize_plot_and_summarize.py", line 157, in plot
    summary = plot_summary(normalized_counts, chromosome)
  File "/opt/liquidator/bamliquidatorbatch/normalize_plot_and_summarize.py", line 140, in plot_summary
    for row in normalized_counts.where(condition):
  File "/usr/lib/python3/dist-packages/tables/table.py", line 1483, in where
    return self._where(condition, condvars, start, stop, step)
  File "/usr/lib/python3/dist-packages/tables/table.py", line 1506, in _where
    self, compiled, condition, condvars, start, stop, step)
  File "/usr/lib/python3/dist-packages/tables/table.py", line 208, in _table__where_indexed
    ncoords = index.search(range_)
  File "/usr/lib/python3/dist-packages/tables/index.py", line 1899, in search
    (start, stop) = self.search_last_row(item)
  File "/usr/lib/python3/dist-packages/tables/index.py", line 1951, in search_last_row
    if nan_aware_gt(item1, b0):
  File "tables/utilsextension.pyx", line 224, in tables.utilsextension.nan_aware_gt
  File "tables/utilsextension.pyx", line 224, in tables.utilsextension.nan_aware_gt
TypeError: '>' not supported between instances of 'str' and 'numpy.bytes_'

----------------------------------------------------------------------
Ran 22 tests in 2.948s

FAILED (errors=8)